name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - staging
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Git SHA and Namespace
        id: meta
        run: |
          echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "namespace=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image to ECR
        run: |
          ECR_REGISTRY="914132589502.dkr.ecr.us-east-1.amazonaws.com"
          ECR_REPOSITORY="web-client"
          SHA="${{ steps.meta.outputs.sha_short }}"
          NS="${{ steps.meta.outputs.namespace }}"
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY"

          echo "🛠️ Building image: $IMAGE_URI:$NS-$SHA"
          docker build -t $IMAGE_URI:$NS-$SHA .

          echo "🏷️ Tagging image as $NS"
          docker tag $IMAGE_URI:$NS-$SHA $IMAGE_URI:$NS

          echo "📤 Pushing image: $NS-$SHA"
          docker push $IMAGE_URI:$NS-$SHA

          echo "📤 Pushing image: $NS"
          docker push $IMAGE_URI:$NS
