on:
  push:
    branches:
      - dev
      - staging
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract short Git SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: Extract namespace from branch
        id: ns
        run: |
          ref="${GITHUB_REF##*/}"
          echo "namespace=$ref" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          ECR_REGISTRY="914132589502.dkr.ecr.us-east-1.amazonaws.com"
          ECR_REPOSITORY="web-client"
          SHA=${{ steps.vars.outputs.sha_short }}
          NS=${{ steps.ns.outputs.namespace }}

          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY"

          echo "🛠️ Building image: $IMAGE_URI:$NS-$SHA"
          docker build -t $IMAGE_URI:$NS-$SHA .

          echo "🏷️ Tagging as latest for $NS"
          docker tag $IMAGE_URI:$NS-$SHA $IMAGE_URI:$NS

          echo "📤 Pushing $NS-$SHA"
          docker push $IMAGE_URI:$NS-$SHA

          echo "📤 Pushing $NS"
          docker push $IMAGE_URI:$NS
