name: Reusable - Build Docker Image and Push to ECR

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      build_args:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract short Git SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image to ECR
        run: |
          ECR_REGISTRY="914132589502.dkr.ecr.us-east-1.amazonaws.com"
          ECR_REPOSITORY="web-client"
          GIT_TAG="${{ steps.vars.outputs.sha_short }}"
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY"

          echo "🛠️ Building Docker image: $IMAGE_URI:$GIT_TAG"
          docker build -t $IMAGE_URI:$GIT_TAG .

          echo "🏷️ Tagging image as latest"
          docker tag $IMAGE_URI:$GIT_TAG $IMAGE_URI:latest

          echo "📤 Pushing both tags to ECR"
          docker push $IMAGE_URI:$GIT_TAG
          docker push $IMAGE_URI:latest
